const state={data:null,current:0,font:19,theme:localStorage.getItem('theme')||'light'};
const $=id=>document.getElementById(id);
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('chapter',String(state.current));localStorage.setItem('font',String(state.font));localStorage.setItem('theme',state.theme)}
function applyTheme(){document.documentElement.dataset.theme=state.theme==='light'?'':state.theme;document.documentElement.style.setProperty('--size',state.font+'px')}
async function init(){const r=await fetch('content/manuscript.json');state.data=await r.json();const saved=Number(localStorage.getItem('chapter'));const f=Number(localStorage.getItem('font'));if(Number.isFinite(saved)&&saved>=0)state.current=Math.min(saved,state.data.units.length-1);if(f>=16&&f<=26)state.font=f;applyTheme();renderFront();renderTOC();updateResume();}
function renderFront(){$('noteLiminaire').innerHTML=state.data.noteLiminaire.map(p=>`<p>${esc(p)}</p>`).join('');$('exergue').textContent=state.data.exergue||'';}
function renderTOC(){const groups=[];state.data.units.forEach((u,i)=>{let g=u.group||'';let grp=groups.find(x=>x.name===g);if(!grp){grp={name:g,items:[]};groups.push(grp)}grp.items.push({...u,index:i})});$('toc').innerHTML=groups.map(g=>`${g.name?`<div class="toc-group">${esc(g.name)}</div>`:''}${g.items.map(u=>`<button class="chapter-link" data-i="${u.index}">${esc(u.title)}</button>`).join('')}`).join('');$('toc').querySelectorAll('button').forEach(b=>b.onclick=()=>openChapter(Number(b.dataset.i)));}
function updateResume(){const has=localStorage.getItem('chapter')!==null;$('resumeBtn').textContent=has?'Reprendre la lecture':'Commencer la lecture';}
function openChapter(i){state.current=i;const u=state.data.units[i];$('home').classList.add('hidden');$('searchView').classList.add('hidden');$('chapterView').classList.remove('hidden');$('chapterMeta').textContent=u.group||'';$('chapterTitle').textContent=u.title;$('chapterText').innerHTML=u.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('');$('prevBtn').disabled=i===0;$('nextBtn').disabled=i===state.data.units.length-1;document.querySelectorAll('#toc button').forEach((b,n)=>b.classList.toggle('active',n===i));window.scrollTo({top:0,behavior:'smooth'});save();updateResume();}
function openHome(){ $('chapterView').classList.add('hidden');$('searchView').classList.add('hidden');$('home').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}
function openSearch(){ $('home').classList.add('hidden');$('chapterView').classList.add('hidden');$('searchView').classList.remove('hidden');closeSidebar();$('searchInput').focus();}
function closeSidebar(){$('sidebar').classList.remove('open');$('backdrop').classList.add('hidden')}
function renderSearch(q){q=q.trim().toLowerCase();if(!q){$('searchCount').textContent='';$('searchResults').innerHTML='';return}let res=[];state.data.units.forEach((u,i)=>u.paragraphs.forEach(p=>{const low=p.toLowerCase();const at=low.indexOf(q);if(at>=0)res.push({i,title:u.title,p,at})}));$('searchCount').textContent=`${res.length} résultat${res.length!==1?'s':''}`;$('searchResults').innerHTML=res.slice(0,80).map(r=>{const a=Math.max(0,r.at-90),b=Math.min(r.p.length,r.at+Math.max(q.length,40)+90);const sn=esc(r.p.slice(a,b));return `<div class="result" data-i="${r.i}"><div class="result-title">${esc(r.title)}</div><div class="result-snippet">… ${sn} …</div></div>`}).join('');$('searchResults').querySelectorAll('.result').forEach(x=>x.onclick=()=>openChapter(Number(x.dataset.i)));}
$('menuBtn').onclick=()=>{$('sidebar').classList.add('open');$('backdrop').classList.remove('hidden')};$('closeMenu').onclick=closeSidebar;$('backdrop').onclick=closeSidebar;$('resumeBtn').onclick=()=>openChapter(state.current);$('prevBtn').onclick=()=>openChapter(state.current-1);$('nextBtn').onclick=()=>openChapter(state.current+1);$('searchBtn').onclick=openSearch;$('themeBtn').onclick=()=>{state.theme=state.theme==='light'?'sepia':state.theme==='sepia'?'dark':'light';applyTheme();save()};$('textMinus').onclick=()=>{state.font=Math.max(16,state.font-1);applyTheme();save()};$('textPlus').onclick=()=>{state.font=Math.min(26,state.font+1);applyTheme();save()};$('searchInput').addEventListener('input',e=>renderSearch(e.target.value));window.addEventListener('scroll',()=>{const d=document.documentElement;const max=d.scrollHeight-d.clientHeight;const pct=max?d.scrollTop/max*100:0;$('progressBar').style.width=pct+'%'});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar();if(e.key==='/'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();openSearch()}});init();
